server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
          - id: payment_routh #路由ID，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
            uri: lb:http://cloud-payment-service #匹配后提供服务的路由地址
            predicates:
              - Path=/payment/get/** #断言，路径相匹配的进行路由
              - After=2020-03-17T16:48:19.650+08:00[Asia/Shanghai] #在某个时间之后才可以访问ZonedDateTime
#              - Cookie=username,fuxl
#              - Header=X-Request-id, \d+
#              - Method=GET
#              -Query=username, \d+

          - id: payment_routh2
#          uri: http://localhost:8001
            uri: lb:http://cloud-payment-service
            predicates:
              - Path=/payment/lb/**


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:8761/eureka  #单机版本
      defaultZone: http://eureka7001.com:7001/eureka  #单机版本
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本
      #访问路径可以显示IP地址


